---
dist: bionic

language: generic

env:
  global:
    - UBPFCOMMIT=644ad3ded2f015878f502765081e166ce8112baf
    - DPDKVER=19.11
    - SPDKVER=19.10.1
  matrix:
    - CC=gcc-7
    - CC=clang-6.0

addons:
  apt:
    packages:
      - build-essential
      - clang-6.0
      - clang-format-6.0
      - curl
      - doxygen
      - gcc-7
      - gcc-multilib
      - go-bindata
      - libelf-dev
      - libnuma-dev
      - libssl-dev
      - liburcu-dev
      - linux-headers-$(uname -r)
      - linux-libc-dev
      - ninja-build
      - pkg-config
      - python3.8
      - python3-distutils
      - rake
      - socat
      - yamllint

cache:
  npm: true
  pip: true
  directories:
    - $HOME/dpdk-$DPDKVER
    - $HOME/spdk-$SPDKVER

before_install:
  - eval "$(gimme 1.x)"
  - nvm install 12
  - |
    : install meson
    cd $HOME
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    sudo python3.8 get-pip.py
    sudo pip install meson

install:
  - |
    : install uBPF
    cd $HOME
    curl -L https://github.com/iovisor/ubpf/archive/$UBPFCOMMIT.tar.gz | tar -xz
    cd ubpf-$UBPFCOMMIT/vm
    make
    sudo install -d /usr/local/include /usr/local/lib
    sudo install -m 0644 -t /usr/local/include/ inc/ubpf.h
    sudo install -m 0644 -t /usr/local/lib/ libubpf.a
  - |
    : install DPDK
    cd $HOME
    if [[ -f dpdk-$DPDKVER/build/lib/librte_eal.so ]]; then
      cd dpdk-$DPDKVER/build
    else
      curl -L http://fast.dpdk.org/rel/dpdk-$DPDKVER.tar.xz | tar -xJ
      cd dpdk-$DPDKVER
      meson -Dtests=false --libdir=lib build
      cd build
      ninja
    fi
    sudo ninja install
    sudo find /usr/local/lib -name 'librte_*.a' -delete
    sudo install -m 0644 -t /usr/local/include/ \
      ../lib/librte_bpf/rte_bpf.h ../lib/librte_bpf/bpf_def.h
    sudo ldconfig
  - |
    : install SPDK
    cd $HOME
    if ! [[ -f spdk-$SPDKVER/build/lib/libspdk_env_dpdk.so ]]; then
      curl -L https://github.com/spdk/spdk/archive/v$SPDKVER.tar.gz | tar -x$z
    fi
    cd spdk-$SPDKVER
    sed '/libfuse3-dev/ d' ./scripts/pkgdep.sh | sudo bash
    if ! [[ -f spdk-$SPDKVER/build/lib/libspdk_env_dpdk.so ]]; then
      ./configure --enable-debug --disable-tests --with-shared \
        --with-dpdk=/usr/local --without-vhost --without-isal --without-fuse
      make -j$(nproc)
    fi
    sudo make install
    sudo ldconfig

before_script:
  - |
    export GOPATH=$HOME/go
    mkdir -p $GOPATH/src
    cp -r $TRAVIS_BUILD_DIR $GOPATH/src/ndn-dpdk

script:
  - cd $GOPATH/src/ndn-dpdk
  - npm install
  - make godeps
  - make goget
  - make
  - make clean
  - RELEASE=1 make cmds
