---
# yamllint disable rule:line-length

dist: bionic

language: generic

env:
  global:
    - UBPFCOMMIT=089f6279752adfb01386600d119913403ed326ee
    - DPDKVER=20.05
    - SPDKVER=20.04.1
    - TEST_ACCEPTABLE_FAILURES="diskstore|ethface|fetch|fwdp|pingclient|pingserver"
  matrix:
    - CC=gcc-7
    - CC=gcc-8
    - CC=clang-8

addons:
  apt:
    sources:
      - sourceline: deb https://deb.nodesource.com/node_14.x bionic main
        key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    packages:
      - build-essential
      - clang-8
      - clang-format-8
      - curl
      - doxygen
      - gcc-8
      - gcc-multilib
      - go-bindata
      - libelf-dev
      - libnuma-dev
      - libssl-dev
      - liburcu-dev
      - linux-libc-dev
      - nodejs
      - pkg-config
      - python3-distutils
      - yamllint

cache:
  npm: true
  pip: true
  directories:
    - $HOME/dpdk-$DPDKVER
    - $HOME/spdk-$SPDKVER
    - $HOME/go/pkg

before_install:
  - eval "$(gimme 1.x)"
  - |
    : install pip dependencies
    cd $HOME
    curl https://bootstrap.pypa.io/get-pip.py | sudo python3
    sudo pip install -U meson ninja

install:
  - |
    : install jsonrpc2client
    curl -L https://github.com/powerman/rpc-codec/releases/download/v1.1.3/jsonrpc2client-linux-x86_64 | \
      sudo install /dev/stdin /usr/local/bin/jsonrpc2client
  - |
    : install uBPF
    cd $HOME
    curl -L https://github.com/iovisor/ubpf/archive/$UBPFCOMMIT.tar.gz | tar -xz
    cd ubpf-$UBPFCOMMIT/vm
    make
    sudo make install
  - |
    : install DPDK
    cd $HOME
    if [[ -f dpdk-$DPDKVER/build/lib/librte_eal.so ]]; then
      cd dpdk-$DPDKVER/build
    else
      curl -L https://static.dpdk.org/rel/dpdk-$DPDKVER.tar.xz | tar -xJ
      cd dpdk-$DPDKVER
      meson -Dtests=false --libdir=lib build
      cd build
      ninja
    fi
    sudo ninja install
    sudo find /usr/local/lib -name 'librte_*.a' -delete
    sudo ldconfig
  - |
    : install SPDK
    cd $HOME
    if ! [[ -f spdk-$SPDKVER/build/lib/libspdk_env_dpdk.so ]]; then
      curl -L https://github.com/spdk/spdk/archive/v$SPDKVER.tar.gz | tar -xz
    fi
    cd spdk-$SPDKVER
    sudo ./scripts/pkgdep.sh
    if ! [[ -f build/lib/libspdk_env_dpdk.so ]]; then
      ./configure --enable-debug --disable-tests --with-shared \
        --with-dpdk=/usr/local --without-vhost --without-isal --without-fuse
      make -j$(nproc)
    fi
    sudo make install
    sudo ldconfig

before_script:
  - |
    : configure hugepages
    echo 2048 | sudo tee /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages >/dev/null
    sudo mkdir -p /mnt/huge2M
    sudo mount -t hugetlbfs nodev /mnt/huge2M -o pagesize=2M
  - cd $TRAVIS_BUILD_DIR

script:
  - npm install
  - make lint && [[ $(git status --porcelain | tee /dev/stderr | wc -l) -eq 0 ]]
  - make
  - MK_GOTEST_FILTER="/${TEST_ACCEPTABLE_FAILURES}/ d" make test
  - MK_GOTEST_FILTER="/${TEST_ACCEPTABLE_FAILURES}/! d" make test || true
  - make clean
  - RELEASE=1 make
  - sudo make install
  - make docs
