# NDN-DPDK initialization configuration
---

# MEMORY POOL
# 'capacity' affects hugepage memory usage; (2^q-1) is optimal.
# 'cachesize' cannot exceed 512; (capacity % cachesize == 0) is optimal.
# 'dataroomsize' should be greater than MTU.
# Each NUMA socket has its own mempool with the given name.
mempool:
  IND:  # indirect mbufs
    capacity: 2097151
    cachesize: 337
  ETHRX:  # RX Ethernet frames
    capacity: 1048575
    cachesize: 465
    dataroomsize: 2000
  NAME:  # name linearize
    capacity: 65535
    cachesize: 255
  HDR:  # TX Ethernet+NDNLP+Interest headers
    capacity: 65535
    cachesize: 255
  INTG:  # modifying Interest guiders
    capacity: 65535
    cachesize: 255
  INT:  # TX Ethernet+NDNLP and encoding Interest
    capacity: 65535
    cachesize: 255
  DATA:  # TX Ethernet+NDNLP and encoding Data
    capacity: 65535
    cachesize: 255
    dataroomsize: 2000

# LCORE ALLOCATION
# This is a mapping from LCore role to its reservations.
# Roles for ndnfw-dpdk: RX, TX, CRYPTO, FWD.
# Roles for ndnping-dpdk: RX, TX, SVR, CLIR, CLIT.
# Within each role:
# 'lcores' is a list of lcores reserved for a role.
# 'pernuma' is a map of { NumaSocket => max number of lcores } for a role.
# Leaving this section blank results in default allocation.
lcorealloc:
# ROLE1: # this role has lcore 1 and lcore 3
#   lcores: [1, 3]
# ROLE2: # this role can have up to 3 and 2 lcores on two NUMA sockets
#   pernuma:
#     0: 3
#     1: 2

# FACE CREATION
face:
  # whether to enable Ethernet faces
  enableeth: true
  # whether to disable RxFlow dispatching
  ethdisablerxflow: false
  # Ethernet device MTU
  ethmtu: 1500
  # Ethernet RX queue capacity
  ethrxqframes: 4096
  # Ethernet before-TX queue capacity
  ethtxqpkts: 256
  # Ethernet after-TX queue capacity
  ethtxqframes: 4096

  # whether to enable socket faces
  enablesock: true
  # socket before-TX queue capacity
  socktxqpkts: 256
  # socket after-TX queue capacity
  socktxqframes: 1024

  # ChanRxGroup queue capacity (shared among all socket/mock faces)
  chanrxgframes: 4096

# NDT
ndt:
  # Names are dispatched using prefix with this number of components.
  prefixlen: 2
  # There are (2^indexbits) elements.
  indexbits: 16
  # Collect per-element sample every (2^samplefreq) lookups. Must not exceed 30.
  samplefreq: 8

# FIB
fib:
  # Capacity in each partition. Affects hugepage memory usage.
  # (2^q-1) is optimal.
  maxentries: 65535
  # Number of hash table buckets in each partition. Must be power of 2.
  nbuckets: 256
  # 'M' parameter in 2-stage LPM algorithm.
  # Should be greater than length of most FIB entry names.
  startdepth: 8

# FORWARDER DATA PLANE
fwdp:
  # Capacity of queue between FwInput and FwFwd.
  fwdqueuecapacity: 128
  # Collect RX-FwFwd latency sample every 2^latencysamplefreq packets.
  # Must not exceed 30.
  latencysamplefreq: 16
  # Capacity of PCCT. (2^q-1) is optimal.
  pcctcapacity: 131071
  # Capacity of CS in-memory direct entries. Must not exceed pcctcapacity.
  cscapmd: 32768
  # Capacity of CS in-memory indirect entries. Must not exceed pcctcapacity.
  cscapmi: 32768

  # True to create multicast Ethernet faces automatically.
  autofaces: false
