# NDN-DPDK initialization configuration
---

# MEMORY POOL
# 'Capacity' affects hugepage memory usage; (2^q-1) is optimal.
# 'CacheSize' cannot exceed 512; (Capacity % CacheSize == 0) is optimal.
# 'DataroomSize' should be greater than MTU.
# Each NUMA socket has its own mempool with the given name.
Mempool:
  IND:  # indirect mbufs
    Capacity: 2097151
    CacheSize: 337
  ETHRX:  # RX Ethernet frames
    Capacity: 1048575
    CacheSize: 465
    DataroomSize: 2200
  NAME:  # name linearize
    Capacity: 65535
    CacheSize: 255
  HDR:  # TX Ethernet+NDNLP+Interest headers
    Capacity: 65535
    CacheSize: 255
  INTG:  # modifying Interest guiders
    Capacity: 65535
    CacheSize: 255
  INT:  # TX Ethernet+NDNLP and encoding Interest
    Capacity: 65535
    CacheSize: 255
  DATA0:  # TX Ethernet+NDNLP+Data name prefix
    Capacity: 65535
    CacheSize: 255
  DATA1:  # TX Data name suffix and payload
    Capacity: 255
    CacheSize: 0
    DataroomSize: 9000

# LCORE ALLOCATION
# This is a mapping from LCore role to its reservations.
# Roles for ndnfw-dpdk: RX, TX, CRYPTO, FWD.
# Roles for ndnping-dpdk: RX, TX, SVR, CLIR, CLIT.
# Within each role:
# 'lcores' is a list of lcores reserved for a role.
# 'pernuma' is a map of { NumaSocket => max number of lcores } for a role.
# Leaving this section blank results in default allocation.
LCoreAlloc:
# ROLE1: # this role has lcore 1 and lcore 3
#   lcores: [1, 3]
# ROLE2: # this role can have up to 3 and 2 lcores on two NUMA sockets
#   pernuma:
#     0: 3
#     1: 2

# FACE CREATION
Face:
  # whether to enable Ethernet faces
  EnableEth: true
  # whether to disable RxFlow dispatching
  EthDisableRxFlow: false
  # Ethernet device MTU
  EthMtu: 1500
  # Ethernet RX queue capacity
  EthRxqFrames: 4096
  # Ethernet before-TX queue capacity
  EthTxqPkts: 256
  # Ethernet after-TX queue capacity
  EthTxqFrames: 4096

  # whether to enable socket faces
  EnableSock: true
  # socket before-TX queue capacity
  SockTxqPkts: 256
  # socket after-TX queue capacity
  SockTxqFrames: 1024

  # ChanRxGroup queue capacity (shared among all socket/mock faces)
  ChanRxgFrames: 4096

# NDT
Ndt:
  # Names are dispatched using prefix with this number of components.
  PrefixLen: 2
  # There are (2^IndexBits) elements.
  IndexBits: 16
  # Collect per-element sample every (2^SampleFreq) lookups. Must not exceed 30.
  SampleFreq: 8

# FIB
Fib:
  # Capacity in each partition. Affects hugepage memory usage.
  # (2^q-1) is optimal.
  MaxEntries: 65535
  # Number of hash table buckets in each partition. Must be power of 2.
  NBuckets: 256
  # 'M' parameter in 2-stage LPM algorithm.
  # Should be greater than length of most FIB entry names.
  StartDepth: 8

# FORWARDER DATA PLANE
Fwdp:
  # Settings of Interest queue between FwInput and FwFwd.
  FwdInterestQueue:
    Capacity: 131072
    DequeueBurstSize: 32
  # Settings of Data queue between FwInput and FwFwd.
  FwdDataQueue:
    Capacity: 131072
    DequeueBurstSize: 64
  # Settings of Nack queue between FwInput and FwFwd.
  FwdNackQueue:
    Capacity: 131072
    DequeueBurstSize: 64
  # Collect RX-FwFwd latency sample every 2^LatencySampleFreq packets.
  # Must not exceed 30.
  LatencySampleFreq: 16
  # Capacity of PCCT. (2^q-1) is optimal.
  PcctCapacity: 131071
  # Capacity of CS in-memory direct entries. Twice as many PCCT entries could
  # be occupied due to ghost lists in ARC algorithm.
  CsCapMd: 32768
  # Capacity of CS in-memory indirect entries.
  CsCapMi: 32768
