---
# yamllint disable rule:line-length rule:truthy

name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        compiler:
          - gcc-7
          - gcc-10
          - clang-11
      fail-fast: false
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: compilers
        name: Install compilers and tools
        run: |
          wget https://apt.llvm.org/llvm.sh
          sudo bash ./llvm.sh 11
          sudo apt-get install $CC clang-format-11 doxygen gcc-multilib llvm-11 libelf-dev libpcap-dev liburcu-dev linux-libc-dev python3.8 python3-setuptools
          for C in go gofmt node; do
            sudo update-alternatives --remove-all $C || true
            sudo update-alternatives --install /usr/bin/$C $C $(command -v $C) 1
          done
          go install honnef.co/go/tools/cmd/staticcheck@latest
          sudo update-alternatives --remove-all python || true
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
          pip install meson
          echo '::set-output name=meson::'$(meson --version)
      - name: Install uBPF
        run: |
          mkdir -p $HOME/ubpf
          cd $HOME/ubpf
          curl -fsLS https://github.com/iovisor/ubpf/archive/$UBPFCOMMIT.tar.gz | tar -xz --strip-components=1
          cd vm
          make
          sudo make install
        env:
          UBPFCOMMIT: 0afd63055b84808853e6e841771e14921aa2d29e
      - name: Install liburing
        run: |
          mkdir -p $HOME/liburing
          cd $HOME/liburing
          curl -fsLS https://github.com/axboe/liburing/archive/$URINGVER.tar.gz | tar -xz --strip-components=1
          ./configure --prefix=/usr/local
          make -C src
          sudo make install
        env:
          CXX: false
          URINGVER: liburing-2.2
      - name: Cache DPDK and SPDK
        uses: actions/cache@v3
        with:
          path: ~/setup-dpdk
          key: ${{ matrix.compiler }}_${{ steps.compilers.outputs.meson }}_20221011
      - uses: yoursunny/setup-dpdk@main
        with:
          dpdk-version: '22.07'
          spdk-version: '22.09'
          target-arch: haswell
      - uses: actions/checkout@v3
      - name: Build NDN-DPDK in debug mode
        run: |
          corepack pnpm install
          make
          sudo make install
          for D in sample/activate sample/benchmark sample/status; do
            pushd $D
            corepack pnpm install
            popd
          done
          sudo make uninstall
        env:
          NDNDPDK_MK_THREADSLEEP: 1
      - name: Run required unit tests
        run: |
          echo 'bdev|disk|ethface|fetch|fileserver|fwdp|memifface|memiftransport|tgconsumer|tgproducer' >~/acceptable-failures.txt
          MK_GOTEST_FILTER="/$(cat ~/acceptable-failures.txt)/ d" make test
        env:
          NDNDPDK_MK_THREADSLEEP: 1
      - name: Run optional unit tests
        run: |
          MK_GOTEST_FILTER="/$(cat ~/acceptable-failures.txt)/! d" make test
        env:
          NDNDPDK_MK_THREADSLEEP: 1
        continue-on-error: true
      - name: Check code style
        run: |
          make lint
          git diff --exit-code
      - name: Build docs
        run: make doxygen
      - name: Build docs site
        run: mk/netlify.sh
        if: ${{ matrix.compiler == 'gcc-7' && github.repository == 'yoursunny/ndn-dpdk' && github.event_name == 'push' }}
      - name: Deploy docs site
        uses: South-Paw/action-netlify-deploy@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: a0fbfa66-eecb-46d0-9e0b-093ddd1d0fad
          build-dir: ./build/netlify/
        if: ${{ matrix.compiler == 'gcc-7' && github.repository == 'yoursunny/ndn-dpdk' && github.event_name == 'push' }}
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3
        with:
          tags: ndn-dpdk
          context: .  # don't use git context: it won't download .git directory into build context
          build-args: |
            MAKE_ENV=NDNDPDK_MK_RELEASE=1
      - name: Show image size
        run: docker image inspect -f '{{.Size}}' ndn-dpdk
      - name: List files in image
        run: docker run --rm ndn-dpdk find /usr/local
  library:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/tinygo_${TINYGO_VERSION}_amd64.deb
          sudo dpkg -i tinygo_${TINYGO_VERSION}_amd64.deb
        working-directory: /tmp
        env:
          TINYGO_VERSION: "0.26.0"
      - uses: actions/checkout@v3
      - name: Build for Linux without cgo
        run: |
          go build -v -o /dev/null ./ndn/...
          go build -v -o /dev/null ./cmd/ndndpdk-ctrl
          go build -v -o /dev/null ./cmd/ndndpdk-godemo
        env:
          CGO_ENABLED: 0
      - name: Build for Windows without cgo
        run: |
          go build -v -o /dev/null ./ndn/...
        env:
          CGO_ENABLED: 0
          GOOS: windows
      - name: Build with TinyGo
        run: |
          tinygo build -o /dev/null -target=wasm ./ndn/ndntestenv/tiny
